"""Added fileds for agent form

Revision ID: 2b6d8b53d22d
Revises: 9f720109393e
Create Date: 2026-01-29 15:29:56.848416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b6d8b53d22d'
down_revision: Union[str, Sequence[str], None] = '9f720109393e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_pickup_details', sa.Column('photos_metadata', sa.JSON(), nullable=True))
    op.add_column('agent_pickup_details', sa.Column('photos_blob', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_agent_pickup_details_agent_id'), 'agent_pickup_details', ['agent_id'], unique=False)
    op.drop_column('agent_pickup_details', 'photos')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.add_column('agent_pickup_details', sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_pickup_details_agent_id'), table_name='agent_pickup_details')
    op.drop_column('agent_pickup_details', 'photos_blob')
    op.drop_column('agent_pickup_details', 'photos_metadata')
    # ### end Alembic commands ###
