"""add coupon_id to orders

Revision ID: 53a6ade8ccee
Revises: h1i2j3k4l5
Create Date: 2026-03-20 20:44:36.796472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a6ade8ccee'
down_revision: Union[str, Sequence[str], None] = 'h1i2j3k4l5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code_applied', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('coupon_bonus_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_phone_search'), table_name='phones_list', postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_phones_list_search_vector'), table_name='phones_list', postgresql_using='gin')
    op.create_index(op.f('ix_phones_list_search_text'), 'phones_list', ['search_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_list_search_text'), table_name='phones_list')
    op.create_index(op.f('idx_phones_list_search_vector'), 'phones_list', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_phone_search'), 'phones_list', ['search_text'], unique=False, postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'coupon_bonus_amount')
    op.drop_column('orders', 'coupon_code_applied')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
