"""Added orders table

Revision ID: 66ad3985a09e
Revises: 9c64ecaec4af
Create Date: 2026-01-08 01:28:26.801366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ad3985a09e'
down_revision: Union[str, Sequence[str], None] = '9c64ecaec4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('agent_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'accepted_at')
    op.drop_column('orders', 'agent_name')
    op.drop_column('orders', 'agent_id')
    op.drop_column('orders', 'pickup_date')
    # ### end Alembic commands ###
