"""Added phone_list table

Revision ID: 6c9edb616053
Revises: 
Create Date: 2026-01-07 22:42:22.844307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9edb616053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Brand', sa.String(), nullable=False),
    sa.Column('Series', sa.String(), nullable=False),
    sa.Column('Model', sa.String(), nullable=False),
    sa.Column('Storage_Raw', sa.String(), nullable=False),
    sa.Column('Original_Price', sa.Float(), nullable=False),
    sa.Column('Selling_Price', sa.Float(), nullable=False),
    sa.Column('RAM_GB', sa.Float(), nullable=False),
    sa.Column('Internal_Storage_GB', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_list_id'), 'phones_list', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_phones_list_id'), table_name='phones_list')
    op.drop_table('phones_list')
    # ### end Alembic commands ###
