"""Added_Referral

Revision ID: 793535cab72c
Revises: 2b6d8b53d22d
Create Date: 2026-02-04 22:44:37.570879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793535cab72c'
down_revision: Union[str, Sequence[str], None] = '2b6d8b53d22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_for_referrer', sa.Integer(), nullable=False),
    sa.Column('points_for_new_user', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_settings_id'), 'referral_settings', ['id'], unique=False)
    op.create_table('referral_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_codes_code'), 'referral_codes', ['code'], unique=True)
    op.create_index(op.f('ix_referral_codes_expires_at'), 'referral_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_referral_codes_id'), 'referral_codes', ['id'], unique=False)
    op.create_index(op.f('ix_referral_codes_is_active'), 'referral_codes', ['is_active'], unique=False)
    op.create_index(op.f('ix_referral_codes_redeemed_by_user_id'), 'referral_codes', ['redeemed_by_user_id'], unique=False)
    op.create_index(op.f('ix_referral_codes_referrer_id'), 'referral_codes', ['referrer_id'], unique=False)
    op.create_table('referral_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_code_id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('new_user_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded_to_referrer', sa.Integer(), nullable=False),
    sa.Column('points_awarded_to_new_user', sa.Integer(), nullable=False),
    sa.Column('points_awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referral_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_history_id'), 'referral_history', ['id'], unique=False)
    op.create_index(op.f('ix_referral_history_new_user_id'), 'referral_history', ['new_user_id'], unique=False)
    op.create_index(op.f('ix_referral_history_referral_code_id'), 'referral_history', ['referral_code_id'], unique=False)
    op.create_index(op.f('ix_referral_history_referrer_id'), 'referral_history', ['referrer_id'], unique=False)
    op.add_column('users', sa.Column('referral_points', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET referral_points = 0 WHERE referral_points IS NULL")
    op.alter_column('users', 'referral_points', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_points')
    op.drop_index(op.f('ix_referral_history_referrer_id'), table_name='referral_history')
    op.drop_index(op.f('ix_referral_history_referral_code_id'), table_name='referral_history')
    op.drop_index(op.f('ix_referral_history_new_user_id'), table_name='referral_history')
    op.drop_index(op.f('ix_referral_history_id'), table_name='referral_history')
    op.drop_table('referral_history')
    op.drop_index(op.f('ix_referral_codes_referrer_id'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_redeemed_by_user_id'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_is_active'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_id'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_expires_at'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_code'), table_name='referral_codes')
    op.drop_table('referral_codes')
    op.drop_index(op.f('ix_referral_settings_id'), table_name='referral_settings')
    op.drop_table('referral_settings')
    # ### end Alembic commands ###
