"""Added orders table

Revision ID: a98580b2ec68
Revises: 66ad3985a09e
Create Date: 2026-01-08 01:51:32.801047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98580b2ec68'
down_revision: Union[str, Sequence[str], None] = '66ad3985a09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_time', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('agent_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'agent_phone')
    op.drop_column('orders', 'pickup_time')
    # ### end Alembic commands ###
