"""add_agent_email_to_orders

Revision ID: b8d71269870d
Revises: 547745fecaca
Create Date: 2026-01-23 13:39:17.166709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d71269870d'
down_revision: Union[str, Sequence[str], None] = '547745fecaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('agent_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'agent_email')
    # ### end Alembic commands ###
