"""Added images

Revision ID: bd802697a4ad
Revises: 65b2051628ef
Create Date: 2026-02-05 13:07:16.148318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd802697a4ad'
down_revision: Union[str, Sequence[str], None] = '65b2051628ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones_list', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('phones_list', sa.Column('image_blob', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phones_list', 'image_blob')
    op.drop_column('phones_list', 'image_url')
    # ### end Alembic commands ###
