"""Added Latitude and Longitude

Revision ID: cfa3c3831acb
Revises: 6900c4e7b867
Create Date: 2026-01-08 08:47:22.898149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa3c3831acb'
down_revision: Union[str, Sequence[str], None] = '6900c4e7b867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('orders', 'pickup_longitude')
    op.drop_column('orders', 'pickup_latitude')
    # ### end Alembic commands ###
