from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean
from sqlalchemy.sql import func
from backend.shared.db.connections import Base


class ReferralCode(Base):
    """
    Referral codes generated by users for customer acquisition.
    6-digit numerical code, linked to referrer, with expiry time.
    """
    __tablename__ = "referral_codes"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(6), unique=True, index=True, nullable=False)
    referrer_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # User who redeemed this code (if any)
    redeemed_by_user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    
    # Timestamp when code was created
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Timestamp when code expires
    expires_at = Column(DateTime(timezone=True), nullable=False, index=True)
    
    # Timestamp when code was redeemed (if any)
    redeemed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Whether code is still valid (hasn't expired and not redeemed)
    is_active = Column(Boolean, default=True, index=True)


class ReferralSettings(Base):
    """
    Admin-configurable settings for the referral system.
    Single row in the table.
    """
    __tablename__ = "referral_settings"

    id = Column(Integer, primary_key=True, index=True)
    
    # Points awarded to the referrer when a new user signs up with their code
    points_for_referrer = Column(Integer, default=100, nullable=False)
    
    # Points awarded to the new user when they sign up with a referral code
    points_for_new_user = Column(Integer, default=50, nullable=False)
    
    # Validity period of referral code in days
    validity_days = Column(Integer, default=2, nullable=False)
    
    # Timestamp of last update
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class ReferralHistory(Base):
    """
    Track referral redemptions and point awards.
    """
    __tablename__ = "referral_history"

    id = Column(Integer, primary_key=True, index=True)
    
    # The referral code used
    referral_code_id = Column(Integer, ForeignKey("referral_codes.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Referrer (original code creator)
    referrer_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # New user who signed up using the code
    new_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Points awarded to referrer
    points_awarded_to_referrer = Column(Integer, nullable=False)
    
    # Points awarded to new user
    points_awarded_to_new_user = Column(Integer, nullable=False)
    
    # Timestamp when points were awarded
    points_awarded_at = Column(DateTime(timezone=True), server_default=func.now())
